// examples/lovable-react/audit.config.ts
//
// Example configuration for a typical Lovable-built React app.
// This file was generated by vibe-audit after the first audit session.
// Replace all placeholder values with your app's actual values.

import { AppConfig } from '../../engine/audit.config';

export const APP_CONFIG: AppConfig = {
  appName: 'My Lovable App',
  baseUrl: 'https://my-app.lovable.app',
  apiUrl: 'https://my-api.up.railway.app',

  auth: {
    email: 'admin@myapp.com',
    password: 'mypassword',
    successUrlContains: '/dashboard',
  },

  tabs: [
    {
      name: 'Dashboard',
      path: '/dashboard',
      kpis: [
        {
          label: 'Total Users',
          selector: '[data-testid="total-users"], :text("TOTAL USERS") + span, .kpi-card:has-text("Total Users") .value',
          apiEndpoint: '/api/users/count',
          expectedMin: 1,
        },
        {
          label: 'Active Sessions',
          selector: '[data-testid="active-sessions"], .kpi-card:has-text("Active") .value',
          apiEndpoint: '/api/sessions/active',
          expectedMin: 0,
        },
      ],
      lists: [
        {
          label: 'Recent Activity',
          selector: '.activity-item, [data-testid="activity-row"], tbody tr',
          apiEndpoint: '/api/activity',
          minItems: 1,
        },
      ],
      buttons: [
        {
          label: 'Refresh',
          selector: 'button:has-text("Refresh"), button[aria-label="Refresh"]',
          action: 'click',
          expect: 'triggers data refresh API call',
        },
      ],
    },
    {
      name: 'Users',
      path: '/users',
      kpis: [
        {
          label: 'Total Count',
          selector: '.total-count, [data-testid="user-count"]',
          apiEndpoint: '/api/users',
          expectedMin: 1,
        },
      ],
      lists: [
        {
          label: 'Users Table',
          selector: 'tbody tr, [data-testid="user-row"]',
          apiEndpoint: '/api/users',
          minItems: 1,
        },
      ],
      buttons: [
        {
          label: 'New User',
          selector: 'button:has-text("New User"), button:has-text("Add User")',
          action: 'click',
          expect: 'opens new user modal or navigates to /users/new',
        },
      ],
    },
    {
      name: 'Settings',
      path: '/settings',
      kpis: [],
      lists: [],
      buttons: [
        {
          label: 'Save Settings',
          selector: 'button:has-text("Save"), button[type="submit"]',
          action: 'click',
          expect: 'triggers settings save API call, shows success toast',
        },
      ],
    },
  ],

  global: {
    modalClose: '[aria-label="Close"], button:has-text("Cancel"), button:has-text("Close"), .modal-close',
    loadingSpinner: '.loading, .spinner, [data-testid="loading"], .skeleton',
    errorToast: '.error-toast, [data-testid="error"], [role="alert"].error, .toast-error',
    emptyState: '.empty-state, :text("No data"), :text("No results"), :text("Nothing here"), :text("Get started")',
  },

  timing: {
    pageLoad: 2500,
    afterClick: 1200,
    chartRender: 3000,
    apiResponse: 5000,
  },
};
